name: CANC Free Automator

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours automatically
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          
      - name: Execute Automation Script
        run: python canc_automator.py